apiVersion: argoproj.io/v1alpha1
destination:
  namespace: default
  server: https://kubernetes.default.svc
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.6.3
