global:
  # Optional: if you want to use a specific image pull secret
  imagePullSecrets: []

# Deployment configuration
replicaCount: 1

# Container image configuration
image:
  repository: docker.io/bitnami/grafana
  tag: 11.4.0-debian-12-r2
  pullPolicy: IfNotPresent

# Grafana container resources
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 150m
    memory: 192Mi

# Disable persistent storage
persistence:
  enabled: false

# Use emptyDir for data storage
volumes:
  - name: data
    emptyDir: {}

# Volume mount configuration
volumeMounts:
  - name: data
    mountPath: /opt/bitnami/grafana/data

# Environment variables
env:
  # Basic configuration examples
  - name: GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION
    value: "false"
  - name: GF_SECURITY_ADMIN_USER
    value: admin

# Service configuration
service:
  type: ClusterIP
  port: 3000

# Optional: ingress configuration
ingress:
  enabled: false