defaultStorageClass:
  enabled: true

storageClasses:
  - name: ebs-sc
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    volumeBindingMode: WaitForFirstConsumer
    reclaimPolicy: Delete
    parameters:
      # Add any specific parameters here, e.g.:
      encrypted: "true"